CREATE DATABASE DATBAO
--bangr BAO
IF OBJECT_ID('BAO') IS NOT NULL 
DROP TABLE   BAO
GO 
CREATE TABLE BAO
(
	MaToBao VARCHAR(10) PRIMARY KEY,
	TenBao NVARCHAR(50),
	DiaChi NVARCHAR(100)
)
---------BANGR DOCGIA
IF OBJECT_ID('DOCGIA') IS NOT NULL 
DROP TABLE   DOCGIA
GO 
CREATE TABLE DOCGIA
(
	MaDG VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(50),
	NgaySinh DATE,
	GioiTinh VARCHAR(5),
	DiaChi NVARCHAR(100)
)
----bangr DATMUA
IF OBJECT_ID('DATMUA') IS NOT NULL 
DROP TABLE   DATMUA
GO 
CREATE TABLE DATMUA
(
	
	MaDG VARCHAR(10),
	MaToBao VARCHAR(10),
	Quy INT,
	Nam DATE,
	SoLuong INT,
	DonGia MONEY,
	PRIMARY KEY(MaDG,MaToBao),
	FOREIGN KEY (MaDG) REFERENCES  DOCGIA,
	FOREIGN KEY (MaToBao) REFERENCES  BAO
)

---caau 2:
--bangr BAO
IF OBJECT_ID('sp_BAO') IS NOT NULL 
DROP PROC   sp_BAO
GO 
CREATE PROC sp_BAO
	@MaToBao VARCHAR(10),
	@TenBao NVARCHAR(50),
	@DiaChi NVARCHAR(100)
AS
BEGIN
	IF(@MaToBao IS NULL OR @TenBao IS NULL OR @DiaChi IS NULL)
		PRINT N'CHƯA NHẬP ĐỦ THÔNG TIN'
	ELSE IF EXISTS(SELECT * FROM BAO WHERE @MaToBao=MaToBao)
		PRINT N'ĐÃ TỒN TẠI'
	ELSE 
		BEGIN
			INSERT INTO BAO VALUES(@MaToBao ,@TenBao ,@DiaChi )
		END
END
----BẢNG DOCGIA
IF OBJECT_ID('sp_DOCGIA') IS NOT NULL 
DROP PROC sp_DOCGIA
GO 
CREATE PROC sp_DOCGIA
	@MaDG VARCHAR(10),
	@HoTen NVARCHAR(50),
	@NgaySinh DATE,
	@GioiTinh VARCHAR(5),
	@DiaChi NVARCHAR(100)
AS
BEGIN
	IF(@MaDG IS NULL OR @HoTen IS NULL OR @NgaySinh IS NULL OR @GioiTinh IS NULL OR @DiaChi IS NULL)
		PRINT N'CHƯA NHẬP ĐỦ THÔNG TIN'
	ELSE IF EXISTS(SELECT * FROM DOCGIA WHERE @MaDG=MaDG)
		PRINT N'ĐÃ TỒN TẠI'
	ELSE 
		BEGIN
			INSERT INTO DOCGIA VALUES(@MaDG ,@HoTen,@HoTen,@GioiTinh ,@DiaChi)
		END
END

--BẢNG DATMUA
IF OBJECT_ID('sp_DATMUA') IS NOT NULL 
DROP PROC   sp_DATMUA
GO 
CREATE PROC sp_DATMUA	
	@MaDG VARCHAR(10),
	@MaToBao VARCHAR(10),
	@Quy INT,
	@Nam DATE,
	@SoLuong INT,
	@DonGia MONEY
AS
BEGIN
	IF(@MaDG IS NULL OR @MaToBao IS NULL OR @Quy IS NULL OR @Nam IS NULL OR @SoLuong IS NULL OR @DonGia IS NULL)
		PRINT N'CHƯA NHẬP ĐỦ THÔNG TIN'
	ELSE 
		BEGIN
			INSERT INTO DATMUA VALUES(@MaDG,@MaToBao,@Quy,@Nam,@SoLuong,@DonGia)
		END
END


EXEC sp_BAO 'N01',N'NHÂN DÂN',N'TOÀ P'
EXEC sp_BAO 'N02',N'LAO ĐỘNG',N'TOÀ F'
EXEC sp_BAO 'N03',N'THANH NIÊN',N'TOÀ L'


EXEC sp_DOCGIA '001',N'LÊ THỊ NGA','1999/02/06',N'NỮ',N'CẦU GIẤY'
EXEC sp_DOCGIA '002',N'HOÀNG THỊ NGA','1998/03/28',N'NAM',N'THANH XUÂN'
EXEC sp_DOCGIA '003',N'NGUYỄN THỊ NGA','1999/04/16',N'NỮ',N'ĐỐNG ĐA'

EXEC sp_DATMUA '001','N03',4,2019,45,450
EXEC sp_DATMUA '003','N02',3,2022,35,550
EXEC sp_DATMUA '002','N01',2,2021,55,650

