CREATE DATABASE QLSV

IF OBJECT_ID('SINHVIEN') IS NOT NULL 
DROP TABLE   SINHVIEN
GO 
CREATE TABLE SINHVIEN 
(
	MaSV VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(50),
	NgaySinh DATE,
	GioiTinh VARCHAR(5),
	Lop INT
)
----------------------------------------------------
IF OBJECT_ID('MONHOC') IS NOT NULL 
DROP TABLE   MONHOC
GO 
CREATE TABLE MONHOC 
(
	MaMonHoc VARCHAR(10) PRIMARY KEY,
	TenMonHoc NVARCHAR(50),
	SoTinChi INT
)
--------------------------
IF OBJECT_ID('DIEM') IS NOT NULL 
DROP TABLE   DIEM
GO 
CREATE TABLE DIEM 
(
	MaSV VARCHAR(10),
	MaMonHoc VARCHAR(10),
	DiemLan1 FLOAT,
	DiemLan2 FLOAT,
	 PRIMARY KEY(MaSV,MaMonHoc),
	 FOREIGN KEY (MaSV) REFERENCES SINHVIEN,
	 FOREIGN KEY (MaMonHoc) REFERENCES  MONHOC
)

----Baif 2:
---Bangr SINHVIEN
IF OBJECT_ID('sp_SINHVIEN') IS NOT NULL 
DROP PROC   sp_SINHVIEN
GO 
CREATE PROC sp_SINHVIEN 
	@MaSV VARCHAR(10),
	@HoTen NVARCHAR(50),
	@NgaySinh DATE,
	@GioiTinh VARCHAR(5),
	@Lop INT
AS
BEGIN
	IF(@MaSV IS NULL OR @HoTen IS NULL OR @NgaySinh IS NULL OR	@GioiTinh IS NULL OR	@Lop IS NULL)
		PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE IF EXISTS(SELECT * FROM SINHVIEN WHERE @MaSV=MaSV)
		PRINT N'TRÙNG KHOÁ CHÍNH'
	ELSE 
		BEGIN
			INSERT INTO SINHVIEN VALUES(@MaSV, @HoTen,@NgaySinh,@GioiTinh,@Lop)
		END
END

----BẢNG MONHOC
IF OBJECT_ID('sp_MONHOC') IS NOT NULL 
DROP PROC   sp_MONHOC
GO 
CREATE PROC sp_MONHOC 
	@MaMonHoc VARCHAR(10),
	@TenMonHoc NVARCHAR(50),
	@SoTinChi INT
AS
BEGIN
	IF(@MaMonHoc IS NULL OR @TenMonHoc IS NULL OR @SoTinChi IS NULL)
		PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE IF EXISTS(SELECT * FROM MONHOC WHERE @MaMonHoc=MaMonHoc)
		PRINT N'TRÙNG KHOÁ CHÍNH'
	ELSE 
		BEGIN
			INSERT INTO MONHOC VALUES(@MaMonHoc, @TenMonHoc,@SoTinChi)
		END
END

---BẢNG DIEM
IF OBJECT_ID('sp_DIEM') IS NOT NULL 
DROP PROC   sp_DIEM
GO 
CREATE PROC sp_DIEM 
	@MaSV VARCHAR(10),
	@MaMonHoc VARCHAR(10),
	@DiemLan1 FLOAT,
	@DiemLan2 FLOAT
AS
BEGIN
	IF(@MaSV IS NULL OR @MaMonHoc IS NULL OR @DiemLan1 IS NULL OR @DiemLan2 IS NULL)
		PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE 
		BEGIN
			INSERT INTO DIEM VALUES(@MaSV,@MaMonHoc,@DiemLan1,@DiemLan2)
		END
END

EXEC sp_SINHVIEN 'N01',N'LÊ THỊ NGA','2003/04/20',N'NỮ',1
EXEC sp_SINHVIEN 'N02',N'HOÀNG THỊ NGA','2002/03/22',N'NAM',2
EXEC sp_SINHVIEN 'N03',N'NGUYỄN THỊ NGA','2001/02/21',N'NAM',3

EXEC sp_MONHOC '001',N'WEB',3
EXEC sp_MONHOC '002',N'UDPM',4
EXEC sp_MONHOC '003',N'MOBILE',5

EXEC sp_DIEM 'N01','003',8.5,9
EXEC sp_DIEM 'N02','001',7,8
EXEC sp_DIEM 'N03','002',8,8.5

SELECT * FROM SINHVIEN
SELECT * FROM MONHOC
SELECT * FROM DIEM

--CÂU 3:
IF OBJECT_ID('f_SINHVIEN') IS NOT NULL 
DROP FUNCTION   f_SINHVIEN
GO 
CREATE FUNCTION f_SINHVIEN 
(   @HoTen NVARCHAR(50),
	@NgaySinh DATE,
	@GioiTinh VARCHAR(5),
	@Lop INT
)
RETURNS NVARCHAR(100)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM SINHVIEN WHERE @HoTen=HoTen AND @NgaySinh=NgaySinh AND @GioiTinh= GioiTinh AND @Lop=Lop)
		RETURN N'KHÔNG TỒN TẠI SINH VIÊN ĐÓ'
		RETURN N'MÃ SINH VIEN LÀ:' + CAST((SELECT MaSV FROM SINHVIEN 
		WHERE @HoTen=HoTen AND @NgaySinh=NgaySinh AND @GioiTinh= GioiTinh AND @Lop=Lop) 
		AS VARCHAR(10))
END

PRINT dbo.f_SINHVIEN (N'LÊ THỊ NGA','2003/04/20',N'NỮ',1)

---CÂU 4: 
IF OBJECT_ID('vi_Top2') IS NOT NULL 
DROP VIEW   vi_Top2
GO 
CREATE VIEW vi_Top2 
AS
	SELECT TOP 2 SINHVIEN.MaSV, HoTen,TenMonHoc, DiemLan1, DiemLan2, SUM(DiemLan1 + DiemLan2) AS N'Tổng điểm'
	FROM SINHVIEN JOIN DIEM ON DIEM.MaSV=SINHVIEN.MaSV 
				  JOIN MONHOC ON DIEM.MaMonHoc=MONHOC.MaMonHoc
	GROUP BY SINHVIEN.MaSV, HoTen,TenMonHoc, DiemLan1, DiemLan2
	ORDER BY SUM(DiemLan1 + DiemLan2)  DESC

	SELECT * FROM vi_Top2 

--CÂU 5:
IF OBJECT_ID('sp_Xoa') IS NOT NULL 
DROP PROC   sp_Xoa
GO 
CREATE PROC sp_Xoa @Diem INT
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			DECLARE @Table TABLE(MaSV VARCHAR(10))
			INSERT INTO @Table 
			SELECT SINHVIEN.MaSV FROM SINHVIEN JOIN DIEM ON DIEM.MaSV=SINHVIEN.MaSV
			WHERE ((DiemLan1+DiemLan2)/2) > @Diem

			DELETE FROM DIEM WHERE MaSV IN (SELECT MaSV FROM @Table)
			DELETE FROM SINHVIEN WHERE MaSV IN (SELECT MaSV FROM @Table)
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH 
END


EXEC sp_Xoa 8

SELECT * FROM DIEM