CREATE DATABASE V1

IF OBJECT_ID('BAO') IS NOT NULL
DROP TABLE BAO
GO
CREATE TABLE BAO
(
	MaToBao VARCHAR(10) PRIMARY KEY,
	TenBao NVARCHAR(50),
	DiaChi NVARCHAR(50)
)

IF OBJECT_ID('DOCGIA') IS NOT NULL
DROP TABLE DOCGIA
GO
CREATE TABLE DOCGIA
(
	MaDG VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(50),
	NgaySinh DATE,
	GioiTinh VARCHAR(5),
	DiaChi NVARCHAR(50)
)


IF OBJECT_ID('DATMUA') IS NOT NULL
DROP TABLE DATMUA
GO
CREATE TABLE DATMUA
(
	MaDG VARCHAR(10) ,
	MaToBao VARCHAR(10),
	Quy INT,
	Nam INT,
	SoLuong INT,
	DonGia MONEY,
	PRIMARY KEY(MaDG,MaToBao),
	FOREIGN KEY (MaDG) REFERENCES DOCGIA,
	FOREIGN KEY (MaToBao) REFERENCES BAO
)


---BAIF 2:
IF OBJECT_ID('sp_BAO') IS NOT NULL
DROP PROC sp_BAO
GO
CREATE PROC sp_BAO
	@MaToBao VARCHAR(10),
	@TenBao NVARCHAR(50),
	@DiaChi NVARCHAR(50)
AS
BEGIN 
	IF(@MaToBao IS NULL OR @TenBao IS NULL OR @DiaChi IS NULL)
		PRINT N'THIEEUS THONG TIN'
	ELSE IF EXISTS(SELECT * FROM BAO WHERE MaToBao=@MaToBao)
		PRINT N'TRUNGF KHOA CHINH'
	ELSE
		BEGIN 
			INSERT INTO BAO VALUES(@MaToBao, @TenBao, @DiaChi)
		END
END

EXEC sp_BAO 'N01',N'NHÂN DÂN',N'TOA P'
EXEC sp_BAO 'N02',N'LAO DONG',N'TOA L'
EXEC sp_BAO 'N03',N'THANH NIÊN',N'TOA F'

SELECT * FROM BAO
-----------------
IF OBJECT_ID('sp_DOCGIA') IS NOT NULL
DROP PROC sp_DOCGIA
GO
CREATE PROC sp_DOCGIA
	@MaDG VARCHAR(10),
	@HoTen NVARCHAR(50),
	@NgaySinh DATE,
	@GioiTinh VARCHAR(5),
	@DiaChi NVARCHAR(50)
AS
BEGIN 
	IF(@MaDG IS NULL OR @HoTen IS NULL OR @NgaySinh IS NULL OR @GioiTinh IS NULL OR @DiaChi IS NULL)
		PRINT N'THIẾU  THONG TIN'
	ELSE IF EXISTS(SELECT * FROM DOCGIA WHERE @MaDG=MaDG)
		PRINT N'TRÙNG KHOÁ CHÍNH'
	ELSE
		BEGIN 
			INSERT INTO DOCGIA VALUES(@MaDG,@HoTen,@NgaySinh,@GioiTinh, @DiaChi)
		END
END

EXEC sp_DOCGIA '001',N'LÊ THỊ NGA','2003/04/20',N'NỮ',N'CẦU DIỄN'
EXEC sp_DOCGIA '002',N'LÊ THỊ NGA A','2002/04/20',N'NAM',N'PHÚC DIỄN'
EXEC sp_DOCGIA '003',N'LÊ THỊ NGA B','2001/04/20',N'NỮ',N'ĐỨC DIỄN'

-----
IF OBJECT_ID('sp_DATMUA') IS NOT NULL
DROP PROC sp_DATMUA
GO
CREATE PROC sp_DATMUA
	@MaDG VARCHAR(10) ,
	@MaToBao VARCHAR(10),
	@Quy INT,
	@Nam INT,
	@SoLuong INT,
	@DonGia MONEY
AS
BEGIN 
	IF(@MaDG IS NULL OR @MaToBao IS NULL OR @Quy IS NULL OR @Nam IS NULL OR @SoLuong IS NULL OR @DonGia IS NULL)
		PRINT N'THIẾU  THONG TIN'
	ELSE
		BEGIN 
			INSERT INTO DATMUA VALUES(@MaDG,@MaToBao,@Quy,@Nam,@SoLuong,@DonGia)
		END
END


EXEC sp_DATMUA '001','N03',2,2019,45,450
EXEC sp_DATMUA '002','N01',4,2021,40,550
EXEC sp_DATMUA '003','N02',3,2023,35,650

--CÂU 3:
IF OBJECT_ID('f_DOCGIA') IS NOT NULL
DROP FUNCTION f_DOCGIA
GO
CREATE FUNCTION f_DOCGIA
(	
	@HoTen NVARCHAR(50),
	@NgaySinh DATE,
	@GioiTinh VARCHAR(5),
	@DiaChi NVARCHAR(50)
)
RETURNS NVARCHAR(100)
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM DOCGIA WHERE @HoTen=HoTen AND @NgaySinh=NgaySinh AND @GioiTinh=GioiTinh AND @DiaChi=DiaChi)
		RETURN N'KHÔNG CÓ ĐỘC GIẢ NÀY'
		RETURN N'MÃ ĐỘC GIẢ LÀ:'+CAST((SELECT MaDG FROM DOCGIA 
		WHERE @HoTen=HoTen AND @NgaySinh=NgaySinh AND @GioiTinh=GioiTinh AND @DiaChi=DiaChi) 
		AS VARCHAR(10))
END

PRINT dbo.f_DOCGIA (N'LÊ THỊ NGA','2003/04/20',N'NỮ',N'CẦU DIỄN')

---câu4:
IF OBJECT_ID('vi_Top2') IS NOT NULL
DROP VIEW vi_Top2
GO
CREATE VIEW  vi_Top2
AS
	SELECT TOP 2 DOCGIA.MaDG,HoTen,TenBao,SoLuong 
	FROM DOCGIA JOIN DATMUA ON DATMUA.MaDG=DOCGIA.MaDG
				JOIN BAO ON BAO.MaToBao=DATMUA.MaToBao
	ORDER BY SoLuong  DESC 
	
SELECT * FROM vi_Top2

---CÂU 5:
IF OBJECT_ID('sp_Xoa') IS NOT NULL
DROP PROC sp_Xoa
GO
CREATE PROC  sp_Xoa @Min INT ,@Max INT
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			DECLARE @Table TABLE(MaToBao VARCHAR(10))
			INSERT INTO @Table 
			SELECT BAO.MaToBao FROM BAO JOIN DATMUA ON DATMUA.MaToBao=BAO.MaToBao WHERE NAM BETWEEN @Min AND @Max
			DELETE FROM DATMUA WHERE MaToBao IN (SELECT MaToBao FROM @Table)
			DELETE FROM BAO WHERE MaToBao IN (SELECT MaToBao FROM @Table)
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH
END

EXEC sp_Xoa 2022,2024

SELECT * FROM DATMUA