CREATE DATABASE Nhap
GO 
USE Nhap
---BẢNG DEAN
IF OBJECT_ID('DEAN') IS NOT NULL
    DROP TABLE DEAN
GO
CREATE TABLE DEAN 
(
	TENDEAN nvarchar(15) NOT NULL,
	MADA int ,
	DDIEM_DA nvarchar(15) NOT NULL,
	PHONG int NULL,
	CONSTRAINT PK_DEAN PRIMARY KEY (MADA)
)
---BẢNG PHONGBAN
IF OBJECT_ID('PHONGBAN') IS NOT NULL
    DROP TABLE PHONGBAN
GO
CREATE TABLE PHONGBAN
(
	TENPHG nvarchar(15) NOT NULL,
	MAPHG int ,
	TRPHG nvarchar(9) NULL,
	NG_NHANCHUC date NOT NULL,
	CONSTRAINT PK_PHONGBAN PRIMARY KEY (MAPHG)
)
---BẢNG ĐIAIEM_PHG
IF OBJECT_ID('DIADIEM_PHG') IS NOT NULL
    DROP TABLE DIADIEM_PHG
GO
CREATE TABLE DIADIEM_PHG
(
	MAPHG int NOT NULL,
	DIADIEM nvarchar(15) NOT NULL,
	CONSTRAINT PK_DIADIEM_PHG PRIMARY KEY (DIADIEM),
	FOREIGN KEY(MAPHG) REFERENCES PHONGBAN	
)
----BẢNG NHANVIEN
IF OBJECT_ID('NHANVIEN') IS NOT NULL
    DROP TABLE NHANVIEN
GO
CREATE TABLE NHANVIEN
(
	HONV nvarchar(15) NOT NULL,
	TENLOT nvarchar(15) NOT NULL,
	TENNV nvarchar(15) NOT NULL,
	MANV nvarchar(9) NOT NULL  PRIMARY KEY,
	NGSINH datetime NOT NULL,
	DCHI nvarchar(30) NOT NULL,
	PHAI nvarchar(3) NOT NULL,
	LUONG float NOT NULL,
	MA_NQL nvarchar(9) NULL,
	PHG int NULL,
	 

)
----BẢNG THANNHAN
IF OBJECT_ID('THANNHAN') IS NOT NULL
    DROP TABLE THANNHAN
GO
CREATE TABLE THANNHAN
(
	MA_NVIEN nvarchar(9) NOT NULL,
	TENTN nvarchar(15) NOT NULL,
	PHAI nvarchar(3) NOT NULL,
	NGSINH date NOT NULL,
	QUANHE nvarchar(15) NOT NULL,
	PRIMARY KEY (TENTN,MA_NVIEN)
		
)

----BẢNG PHANCONG
IF OBJECT_ID('PHANCONG') IS NOT NULL
    DROP TABLE PHANCONG
GO
CREATE TABLE PHANCONG
(
	MA_NVIEN nvarchar(9) NOT NULL,
	MADA int NOT NULL,
	STT int NOT NULL ,
	THOIGIAN float NOT NULL,
	PRIMARY KEY (STT),
	FOREIGN KEY(MA_NVIEN) REFERENCES THANNHAN(MA_NVIEN),
	FOREIGN KEY(MADA) REFERENCES DEAN(MADA)
)
----BẢNG CONGVIEC
IF OBJECT_ID('CONGVIEC') IS NOT NULL
    DROP TABLE CONGVIEC
GO
CREATE TABLE CONGVIEC
(
	MADA int NOT NULL,
	STT int NOT NULL,
	TEN_CONG_VIEC nvarchar(50) NOT NULL,	
	FOREIGN KEY(MADA) REFERENCES DEAN(MADA),
	FOREIGN KEY(STT) REFERENCES PHANCONG(STT),
	PRIMARY KEY(MADA,STT)
)