---Tính diện tích hình chữ nhật
DECLARE @CHIEUDAI INT, @CHIEURONG INT, @DIENTICH1 INT
SET @CHIEUDAI=40
SET @CHIEURONG= 30 
SELECT @DIENTICH1=@CHIEUDAI*@CHIEURONG
SELECT @DIENTICH1 AS DIEN_TICH_CHU_NHAT

---Tính diện tích hình thang
DECLARE @DAYLON INT, @DAYBE INT, @CHIEUCAO INT, @DIENTICH FLOAT
SET @DAYLON=40
SET @DAYBE= 30 
SET @CHIEUCAO=35
SELECT @DIENTICH=((@DAYLON+ @DAYBE)*@CHIEUCAO)/2
SELECT @DIENTICH AS DIEN_TICH_HINH_THANG

---Sử dụng biến liệt kê nhân viên ở hcm
USE QLDA
DECLARE @NHANVIEN_HCM TABLE(MANV NVARCHAR(9), TENNV NVARCHAR(15))
---CHÈN DỮ LIỆU VÀO BIẾN BẢNG
INSERT INTO @NHANVIEN_HCM
SELECT MANV,TENNV
FROM NHANVIEN
WHERE DCHI LIKE '%HCM'
SELECT * FROM @NHANVIEN_HCM





