CREATE DATABASE QLVT

IF OBJECT_ID('VATTU') IS NOT NULL
DROP TABLE VATTU
GO
CREATE TABLE VATTU
(
	MAVT VARCHAR(5) PRIMARY KEY,
	TENVT NVARCHAR(50),
	DVTINH NVARCHAR(50)
)

IF OBJECT_ID('PHIEUXUAT') IS NOT NULL
DROP TABLE PHIEUXUAT
GO
CREATE TABLE PHIEUXUAT
(
	SOPX VARCHAR(5) PRIMARY KEY,
	NGAYXUAT DATE
)

IF OBJECT_ID('CTPXUAT') IS NOT NULL
DROP TABLE CTPXUAT
GO
CREATE TABLE CTPXUAT
(
	SOPX VARCHAR(5) ,
	MAVT VARCHAR(5),
	SLXUAT INT,
	DONGIA MONEY,
	PRIMARY KEY (SOPX,MAVT),
	FOREIGN KEY (SOPX) REFERENCES PHIEUXUAT,
	FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT)
)

--------------------------------------
--CÂU 2: THÊM THÔNG TIN
--BẢNG VATTU
IF OBJECT_ID('insert_VATTU') IS NOT NULL
DROP PROC insert_VATTU
GO
CREATE PROC insert_VATTU
	@MAVT VARCHAR(5),
	@TENVT NVARCHAR(50),
	@DVTINH NVARCHAR(50)
AS
	BEGIN
		IF(@MAVT IS NULL OR @TENVT IS NULL OR @DVTINH IS NULL)
			PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
		ELSE IF  EXISTS (SELECT MAVT FROM VATTU WHERE MAVT=@MAVT)
			PRINT N' MÃ VT NÀY ĐÃ TỒN TẠI'
		ELSE
			BEGIN
				INSERT INTO VATTU VALUES(@MAVT,@TENVT,@DVTINH)
			END
	END
GO

---------BẢNG PHIEUXUAT--------------
IF OBJECT_ID('insert_PHIEUXUAT') IS NOT NULL
DROP PROC insert_PHIEUXUAT
GO
CREATE PROC insert_PHIEUXUAT
	@SOPX VARCHAR(5),
	@NGAYXUAT DATE

AS
BEGIN
	IF(@SOPX IS NULL OR @NGAYXUAT IS NULL)
		PRINT ' THIẾU THÔNG TIN'
	ELSE IF  EXISTS(SELECT SOPX FROM PHIEUXUAT WHERE SOPX=@SOPX)
		PRINT N'SOPX ĐÃ TỒN TẠI'
	ELSE 
		BEGIN
			INSERT INTO PHIEUXUAT VALUES(@SOPX,@NGAYXUAT)
		END
END
GO

------BẢNG CTPXUAT--------------
IF OBJECT_ID('insert_CTPXUAT') IS NOT NULL
DROP PROC insert_CTPXUAT
GO
CREATE PROC insert_CTPXUAT
	@SOPX VARCHAR(5) ,
	@MAVT VARCHAR(5),
	@SLXUAT INT,
	@DONGIA MONEY
AS
	BEGIN
		IF(@SOPX IS NULL OR @MAVT IS NULL OR @SLXUAT IS NULL OR @DONGIA  IS NULL)
			PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
		ELSE 
		 BEGIN 
			INSERT INTO CTPXUAT VALUES(@SOPX,@MAVT, @SLXUAT ,@DONGIA)
		 END
	END
GO

EXEC insert_VATTU '001',N' XI MĂNG',N'KHÔNG HỖ TRỢ'
EXEC insert_VATTU '002',N'TÔN TRẦN',N'HỖ TRỢ'
EXEC insert_VATTU '003',N'CỬA NHÔM',N'HỖ TRỢ'

EXEC insert_PHIEUXUAT 'S1','2022/05/25'
EXEC insert_PHIEUXUAT 'S2','2022/04/20'
EXEC insert_PHIEUXUAT 'S3','2022/06/10'


EXEC insert_CTPXUAT 'S3','002',100,3000
EXEC insert_CTPXUAT 'S1','003',90,4000
EXEC insert_CTPXUAT 'S2','002',150,1000
EXEC insert_CTPXUAT 'S1','001',200,2000


SELECT * FROM VATTU
SELECT * FROM PHIEUXUAT
SELECT * FROM CTPXUAT


------------------
/*BAI3:Viết hàm các tham số đầu vào tương ứng với các cột của bảng VATTU.
Hàm này trả về MaVT thỏa mãn các giá trị được truyền tham số*/
IF OBJECT_ID('f_MaVT') IS NOT NULL
DROP FUNCTION f_MaVT
GO
CREATE FUNCTION f_MaVT (@TENVT NVARCHAR(50),@DVTINH NVARCHAR(50))
RETURNS NVARCHAR(100)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM VATTU WHERE TENVT = @TENVT AND DVTINH = @DVTINH)
		 RETURN N'Không tồn tại khách hàng này'
	
	 RETURN N'Mã VẬT TƯ là: '+CAST((SELECT MAVT FROM VATTU 
	  WHERE TENVT = @TENVT AND DVTINH = @DVTINH)
	  AS VARCHAR(10))
END
GO

PRINT dbo.f_MaVT(N' XI MĂNG',N'KHÔNG HỖ TRỢ')

--CAU 4:TẠO VIEW 
/*Tạo View lưu thông tin của TOP 2 phiếu xuất có ngày xuất gần nhất,
gồm các thông tin
sau: MaVT, TenVT, DVTinh, NgayXuat, TenKH, SLXuat..*/
IF OBJECT_ID('vi_Top2') IS NOT NULL
DROP VIEW vi_Top2
GO
CREATE VIEW vi_Top2
AS
	SELECT TOP 2 VATTU.MAVT,TENVT,DVTINH,NGAYXUAT,SLXUAT
	FROM CTPXUAT JOIN PHIEUXUAT ON PHIEUXUAT.SOPX=CTPXUAT.SOPX
				JOIN VATTU ON VATTU.MAVT=CTPXUAT.MAVT
	ORDER BY NGAYXUAT DESC

SELECT * FROM vi_Top2

--CAU 5:XOA
/*Viết một SP nhận một tham số đầu vào là SLXuat. 
SP này thực hiện thao tác xóa thông
tin vật tư và phiếu xuất tương ứng*/
IF OBJECT_ID('sp_Xoa') IS NOT NULL 
DROP PROC sp_Xoa 
GO 
CREATE PROC sp_Xoa @SLXUAT INT
AS
BEGIN 
	BEGIN TRY
		BEGIN TRAN
			DECLARE @Table TABLE(SOPX VARCHAR(5) ,MAVT VARCHAR(5))
			INSERT INTO @Table
			SELECT SOPX,MAVT FROM CTPXUAT WHERE @SLXUAT=SLXUAT
			
			DELETE FROM CTPXUAT WHERE SOPX IN(SELECT SOPX FROM PHIEUXUAT)
											OR MAVT IN (SELECT MAVT FROM VATTU)
			DELETE FROM PHIEUXUAT WHERE SOPX IN(SELECT SOPX FROM PHIEUXUAT)
			DELETE FROM VATTU WHERE MAVT IN (SELECT MAVT FROM VATTU)
		COMMIT TRAN
	END TRY

	BEGIN CATCH 
		ROLLBACK TRAN 
	END CATCH 
END  

EXEC dbo.sp_Xoa 200

SELECT * FROM CTPXUAT