CREATE DATABASE De3_DATHANG

---1. Tạo cơ sở dữ liệu DATHANG gồm 3 bảng

---------------BẢNG MATHANG---------------------
IF OBJECT_ID('MATHANG') IS NOT NULL
	DROP TABLE MATHANG 
GO
CREATE TABLE MATHANG
(
	MAH VARCHAR(5) PRIMARY KEY,
	TENH NVARCHAR(50),
	LOAIH NVARCHAR(20)
)
------------BẢNG DONHANG--------------------------

IF OBJECT_ID('DONHANG') IS NOT NULL
	DROP TABLE DONHANG 
GO
CREATE TABLE DONHANG
(
	SODH VARCHAR(10) PRIMARY KEY,
	NGAYDH DATE,
	NGAYGH DATE
)
-------------------------BẢNG CTDH-----------------
IF OBJECT_ID('CTDH') IS NOT NULL
	DROP TABLE CTDH 
GO
CREATE TABLE CTDH
(
	SODH VARCHAR(10),
	MAH VARCHAR(5),
	SOLUONG INT,
	DVTINH NVARCHAR(50),
	PRIMARY KEY(SODH,MAH),
	FOREIGN KEY (SODH) REFERENCES DONHANG(SODH),
	FOREIGN KEY (MAH) REFERENCES MATHANG(MAH)
)

--------------------------------------------------
--2. Thêm thông tin vào các bảng

--BẢNG MATHANG
IF OBJECT_ID('sp_MATHANG') IS NOT NULL
	DROP PROC sp_MATHANG 
GO
CREATE PROC sp_MATHANG
	@MAH VARCHAR(5),
	@TENH NVARCHAR(50),
	@LOAIH NVARCHAR(20)
AS
	BEGIN
		IF(@MAH IS NULL OR @TENH IS NULL OR @LOAIH IS NULL)
			PRINT N'THIẾU THÔNG TIN'
		ELSE IF EXISTS (SELECT * FROM MATHANG WHERE @MAH = MAH)
				PRINT N'MẶT HÀNG NÀY ĐÃ TỒN TẠI'
		ELSE
			BEGIN
				INSERT INTO MATHANG VALUES(@MAH , @TENH , @LOAIH)
			END
	END

EXEC sp_MATHANG 'N01',N'GẠO NẾP',N'LOẠI 1'
EXEC sp_MATHANG 'N02',N'BÁNH MỲ',N'LOẠI 2'
EXEC sp_MATHANG 'N03',N'NGŨ CỐC',N'LOẠI 3'

SELECT * FROM MATHANG
GO
---BẢNG DONHANG
IF OBJECT_ID('sp_DONHANG') IS NOT NULL
	DROP PROC sp_DONHANG 
GO
CREATE PROC sp_DONHANG
	@SODH VARCHAR(10),
	@NGAYDH DATE,
	@NGAYGH DATE
AS
	BEGIN
		IF(@SODH IS NULL OR @NGAYDH IS NULL OR @NGAYGH IS NULL)
			PRINT N'THIẾU THÔNG TIN'
		ELSE IF EXISTS (SELECT * FROM DONHANG WHERE SODH=@SODH)
				PRINT N'SODH NÀY ĐÃ TỒN TẠI'
		ELSE
			BEGIN
				INSERT INTO DONHANG VALUES(@SODH,@NGAYDH,@NGAYGH)
			END
	END
EXEC sp_DONHANG '001','2022/03/25','2022/05/20'
EXEC sp_DONHANG '002','2022/03/10','2022/04/28'
EXEC sp_DONHANG '003','2022/04/25','2022/06/25'

SELECT * FROM DONHANG
----BẢNG CTDH
IF OBJECT_ID('sp_CTDH') IS NOT NULL
	DROP PROC sp_CTDH 
GO
CREATE PROC sp_CTDH
	@SODH VARCHAR(10),
	@MAH VARCHAR(5),
	@SOLUONG INT,
	@DVTINH VARCHAR(50)
AS
	BEGIN
		IF(@SODH IS NULL OR @MAH IS NULL OR @SOLUONG IS NULL OR @DVTINH IS NULL)
			PRINT N'THIẾU THÔNG TIN'
		ELSE
			BEGIN
				INSERT INTO CTDH VALUES(@SODH,@MAH,@SOLUONG,@DVTINH)
					PRINT N'THÊM THÀNH CÔNG'
			END
	END

EXEC sp_CTDH '002','N03',30,N'KHÔNG HỖ TRỢ'
EXEC sp_CTDH '001','N02',45,N'HỖ TRỢ'
EXEC sp_CTDH '003','N01',20,N'KHÔNG HỖ TRỢ'

SELECT * FROM CTDH


/*Viết hàm các tham số đầu vào tương ứng với các cột của bảng MATHANG .
Hàm này trả về MaH thỏa mãn các giá trị được truyền tham số.*/

--CÁCH 1 DÙNG HÀM TRẢ VỀ GTRI KIỂU DỮ LIỆU
IF OBJECT_ID('f_MaH') IS NOT NULL
	DROP FUNCTION f_MaH
GO
CREATE FUNCTION f_MaH (@TENH NVARCHAR(50),@LOAIH NVARCHAR(20))
RETURNS  NVARCHAR(100) 
AS
	BEGIN
	IF NOT EXISTS (SELECT * FROM MATHANG WHERE @TENH = TENH AND @LOAIH = LOAIH)
		RETURN N'Không tồn tại khách hàng này'
	
		RETURN N'Mã mạt hàng là:' +CAST((SELECT MAH FROM MATHANG
			WHERE @TENH = TENH AND @LOAIH = LOAIH) 
			AS NVARCHAR(10))		 
	 END
GO

PRINT dbo.f_MaH(N'GẠO NẾP',N'LOẠI 1')

--CÁCH 2:DÙNG HÀM GIÁ TRỊ BẢNG TRẢ VỀ GIÁ TRỊ BẢNG
IF OBJECT_ID('f_MaH') IS NOT NULL
	DROP FUNCTION f_MaH
GO
CREATE FUNCTION f_MaH (@TENH NVARCHAR(50),@LOAIH NVARCHAR(20))
RETURNS TABLE
AS
	RETURN 
	(
		SELECT MAH FROM MATHANG
			WHERE @TENH = TENH AND @LOAIH = LOAIH
	)
SELECT * FROM f_MaH (N'GẠO NẾP',N'LOẠI 1')
---NOTE: ĐỐI VỚI BÀI HÀM PHẢI DÙNG dbo

--CÂU 4
/*Tạo View lưu thông tin của TOP 2 chi tiết đơn hàng 
có số lượng nhất, gồm các thông tin
sau: MaH, TenH, LoaiH, NgayDH, NgayGH, SoLuong*/

IF OBJECT_ID('vi_Top2') IS NOT NULL
	DROP VIEW vi_Top2
GO
CREATE VIEW vi_Top2 
AS
	SELECT TOP 2 MATHANG.MAH, TENH, LOAIH, NGAYDH, NGAYGH,SOLUONG 
	FROM MATHANG JOIN CTDH ON CTDH.MAH=MATHANG.MAH
				JOIN DONHANG ON CTDH.SODH=DONHANG.SODH
	ORDER BY SOLUONG DESC

SELECT * FROM vi_Top2

/*Viết một SP nhận một tham số đầu vào là SoLuong.
SP này thực hiện thao tác xóa thông
tin mặt hàng và đơn hàng tương ứng.*/
IF OBJECT_ID('sp_Xoa') IS NOT NULL
	DROP PROC sp_Xoa
GO
CREATE PROC sp_Xoa @SoLuong INT
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			DECLARE @Table TABLE(SODH VARCHAR(10),MAH VARCHAR(5))
			INSERT INTO @Table SELECT SODH,MAH FROM CTDH WHERE @SoLuong = SOLUONG

			DELETE FROM CTDH WHERE SODH IN (SELECT SODH FROM @Table)
									OR MAH IN(SELECT MAH FROM @Table)
			DELETE FROM DONHANG WHERE SODH IN (SELECT SODH FROM @Table)
			DELETE FROM MATHANG WHERE MAH IN(SELECT MAH FROM @Table)

		COMMIT TRAN
	END TRY

	BEGIN CATCH 
		ROLLBACK TRAN
	END CATCH
END

EXEC dbo.sp_Xoa 30

SELECT * FROM CTDH
SELECT * FROM DONHANG
SELECT * FROM MATHANG