CREATE DATABASE DE4_HOADON_SP


IF OBJECT_ID('HOADON') IS NOT NULL 
DROP TABLE HOADON 
GO
CREATE TABLE HOADON
(
	SOHD VARCHAR(10) PRIMARY KEY,
	NGAYHD DATE,
	TRIGIA NVARCHAR(30)
)

IF OBJECT_ID('SANPHAM') IS NOT NULL 
DROP TABLE SANPHAM
GO

CREATE TABLE SANPHAM
(
	MASP VARCHAR(10) PRIMARY KEY,
	TENSP NVARCHAR(50),
	DVTINH NVARCHAR(30),
	NUOCSX VARCHAR(30)
)


IF OBJECT_ID('CTDH') IS NOT NULL 
DROP TABLE CTDH
GO
CREATE TABLE CTDH
(
	SOHD VARCHAR(10),
	MASP VARCHAR(10),
	SOLUONG INT,
	GIA MONEY
	PRIMARY KEY(SOHD,MASP),
	FOREIGN KEY (SOHD) REFERENCES HOADON,
	FOREIGN KEY (MASP) REFERENCES SANPHAM
)

----BAI 2
---BANGR HOADON
IF OBJECT_ID('sp_HOADON') IS NOT NULL 
DROP PROC sp_HOADON 
GO
CREATE PROC sp_HOADON

	@SOHD VARCHAR(10),
	@NGAYHD DATE,
	@TRIGIA NVARCHAR(30)
AS
BEGIN
	IF(@SOHD IS NULL OR @NGAYHD IS NULL OR @TRIGIA IS NULL)
		PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE IF EXISTS(SELECT * FROM HOADON WHERE @SOHD = SOHD)
		PRINT N'SOHD ĐÃ TỒN TẠI'
	ELSE 
		BEGIN
			INSERT INTO HOADON VALUES(@SOHD,@NGAYHD, @TRIGIA)
		END
END

EXEC sp_HOADON 'N01','2022/04/20',N'LOAI 1'
EXEC sp_HOADON 'N02','2022/03/15',N'LOAI 2'
EXEC sp_HOADON 'N03','2022/02/16',N'LOAI 3'


----BẢNG SANPHAM--------
IF OBJECT_ID('sp_SANPHAM') IS NOT NULL 
DROP PROC sp_SANPHAM 
GO
CREATE PROC sp_SANPHAM
	@MASP VARCHAR(10),
	@TENSP NVARCHAR(50),
	@DVTINH NVARCHAR(30),
	@NUOCSX VARCHAR(30)
AS
BEGIN
	IF(@MASP IS NULL OR @TENSP IS NULL OR @DVTINH IS NULL OR @NUOCSX IS NULL)
		PRINT N'PHẢI NHẬP ĐỦ THONG TIN'
	ELSE IF EXISTS(SELECT * FROM SANPHAM WHERE @MASP=MASP)
		PRINT N'MÃ SẢN PHẨM ĐÃ TỒN TẠI'
	ELSE 
		BEGIN
			INSERT INTO SANPHAM VALUES(@MASP,@TENSP, @DVTINH,@NUOCSX)
		END
END

EXEC sp_SANPHAM 'S1',N'MÌ TÔM',N'HỖ TRỢ',N'VIỆT NAM'
EXEC sp_SANPHAM 'S2',N'MÌ CHÍNH',N'KHÔNG HỖ TRỢ',N'CAMPUCHIA'
EXEC sp_SANPHAM 'S3',N'MUỐI TÂY NINH',N'HỖ TRỢ',N'LÀO'

---BẢNG CTDH
IF OBJECT_ID('sp_CTDH') IS NOT NULL 
DROP PROC sp_CTDH
GO
CREATE PROC sp_CTDH
	@SOHD VARCHAR(10),
	@MASP VARCHAR(10),
	@SOLUONG INT,
	@GIA MONEY
AS
BEGIN 
	IF(@SOHD IS NULL OR @MASP IS NULL OR @SOLUONG IS NULL OR @GIA IS NULL)
		PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE 
		BEGIN 
			INSERT INTO CTDH VALUES(@SOHD,@MASP, @SOLUONG,@GIA)
		END
END


EXEC sp_CTDH 'N01','S2',35,5000
EXEC sp_CTDH 'N03','S1',40,3000
EXEC sp_CTDH 'N02','S3',45,7000


SELECT * FROM HOADON
SELECT * FROM SANPHAM
SELECT * FROM CTDH

--CÂU 3:
/*Viết hàm các tham số đầu vào tương ứng với các cột 
của bảng SANPHAM . Hàm này trả
về MaSP thỏa mãn các giá trị được truyền tham số*/

IF OBJECT_ID('f_MaSP') IS NOT NULL 
DROP FUNCTION f_MaSP
GO
CREATE FUNCTION f_MaSP
(
	@TENSP NVARCHAR(50),
	@DVTINH NVARCHAR(30),
	@NUOCSX VARCHAR(30)
)
RETURNS NVARCHAR(100) 
AS
	BEGIN
		IF NOT EXISTS (SELECT * FROM SANPHAM WHERE @TENSP=TENSP AND @DVTINH=DVTINH AND @NUOCSX=NUOCSX)
			RETURN N'KO CÓ DỮ LIỆU'
			RETURN N'MÃ SẢN PHẨM LÀ:' + CAST((SELECT MASP FROM SANPHAM 
							WHERE @TENSP=TENSP AND @DVTINH=DVTINH AND @NUOCSX=NUOCSX) 
							AS VARCHAR(10))
	END 

PRINT dbo.f_MaSP(N'MÌ TÔM',N'HỖ TRỢ',N'VIỆT NAM')
--
--CÂU4 : VIEW

IF OBJECT_ID('vi_Top2') IS NOT NULL 
DROP VIEW vi_Top2
GO
CREATE VIEW vi_Top2
AS
	SELECT TOP 2 SANPHAM.MASP,TENSP,NUOCSX,NGAYHD,TRIGIA,SOLUONG
	FROM SANPHAM  JOIN  CTDH ON SANPHAM.MASP = CTDH.MASP
				  JOIN HOADON ON HOADON.SOHD=CTDH.SOHD
	ORDER BY SOLUONG DESC
SELECT * FROM vi_Top2

---CÂU 5:XOÁ 
/*Viết một SP nhận một tham số đầu vào là SoLuong.
SP này thực hiện thao tác xóa thông
tin sản phẩm và hóa đơn hàng tương ứng*/

IF OBJECT_ID('sp_Xoa') IS NOT NULL 
DROP PROC sp_Xoa
GO
CREATE PROC sp_Xoa @SOLUONG INT
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			DECLARE @Table TABLE(SOHD VARCHAR(10), MASP VARCHAR(10))
			INSERT INTO @Table 
			SELECT SOHD ,MASP FROM CTDH WHERE SOLUONG = @SOLUONG
			
			DELETE FROM CTDH WHERE MASP IN(SELECT MASP FROM @TABLE) OR SOHD IN (SELECT SOHD FROM @Table)
			DELETE FROM SANPHAM WHERE MASP IN(SELECT MASP FROM @TABLE)
			DELETE FROM HOADON WHERE SOHD IN(SELECT SOHD FROM @TABLE)
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH
END
GO

EXEC dbo.sp_Xoa 40

SELECT * FROM CTDH


