CREATE DATABASE De5_HOADON_KH
---BANG KHACHHANG
IF OBJECT_ID('KHACHHANG') IS NOT NULL 
	DROP TABLE KHACHHANG 
GO 
CREATE TABLE KHACHHANG
(
	MaKH VARCHAR(5) PRIMARY KEY,
	HoTenKH NVARCHAR(50),
	DChiKH NVARCHAR(200), 
	SDTKH VARCHAR(15)
)
--BANG NHANVIEN
IF OBJECT_ID('NHANVIEN') IS NOT NULL 
DROP TABLE NHANVIEN 
GO 
CREATE TABLE NHANVIEN
(
	MaNV VARCHAR(5) PRIMARY KEY,
	HoTenNV NVARCHAR(50),
	DChiNV NVARCHAR(200), 
	SDTNV VARCHAR(15)
)
---BANG HOADON
IF OBJECT_ID('HOADON') IS NOT NULL 
DROP TABLE HOADON 
GO 
CREATE TABLE HOADON
(
	MaNV VARCHAR(5),
	MaKH VARCHAR(5),
	NgayHD DATE,
	TriGia MONEY
	PRIMARY KEY (MaNV,MaKH),
	FOREIGN KEY (MaNV) REFERENCES KHACHHANG,
	FOREIGN KEY (MaKH) REFERENCES NHANVIEN 
)

---BAI 2:THÊM THÔNG TIN
---BẢNG KHACHHANG
IF OBJECT_ID('insert_KHACHHANG') IS NOT NULL 
	DROP PROC insert_KHACHHANG
GO 
CREATE PROC insert_KHACHHANG
	@MaKH VARCHAR(5),
	@HoTenKH NVARCHAR(50),
	@DChiKH NVARCHAR(200), 
	@SDTKH VARCHAR(15)
AS
	BEGIN
		IF(@MaKH IS NULL OR @HoTenKH IS NULL OR @DChiKH IS NULL OR @SDTKH IS NULL)
			PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
		ELSE IF EXISTS(SELECT * FROM KHACHHANG WHERE @MaKH = MaKH)
			PRINT N'Mã Khách hàng đã tồn tại'
		ELSE 
			BEGIN
				INSERT INTO KHACHHANG VALUES(@MaKH, @HoTenKH,@DChiKH,@SDTKH)
			END 
	END
EXEC insert_KHACHHANG 'N01',N'LÊ THỊ NGA',N'THANH HOÁ','0335188503'
EXEC insert_KHACHHANG 'N02',N'LÊ THỊ NGA A',N'THANH HOÁ N','0335188678'
EXEC insert_KHACHHANG 'N03',N'LÊ THỊ NGA B',N'THANH HOÁ T','0335188987'

---BẢNG NHANVIEN
IF OBJECT_ID('insert_NHANVIEN') IS NOT NULL 
DROP PROC insert_NHANVIEN
GO 
CREATE PROC insert_NHANVIEN
	@MaNV VARCHAR(5),
	@HoTenNV NVARCHAR(50),
	@DChiNV NVARCHAR(200), 
	@SDTNV VARCHAR(15)
AS
BEGIN
	IF(@MaNV IS NULL OR @HoTenNV IS NULL OR @DChiNV IS NULL OR @SDTNV IS NULL)
		PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE IF EXISTS(SELECT * FROM NHANVIEN WHERE @MaNV=MaNV)
			PRINT N'Mã NHÂN VIÊN đã tồn tại'
		ELSE 
			BEGIN
				INSERT INTO NHANVIEN VALUES(@MaNV, @HoTenNV,@DChiNV,@SDTNV)
			END 
END

EXEC insert_NHANVIEN '001',N'TRẦN PHƯƠNG NHI',N'HÀ NỘI','0456789567'
EXEC insert_NHANVIEN '002',N'TRẦN PHƯƠNG NHI A',N'HÀ NỘI A','0456789345'
EXEC insert_NHANVIEN '003',N'TRẦN PHƯƠNG NHI B',N'HÀ NỘI B','0456789123'

---BẢNG HOADON
IF OBJECT_ID('insert_HOADON') IS NOT NULL 
DROP PROC insert_HOADON
GO 
CREATE PROC insert_HOADON
	@MaNV VARCHAR(5),
	@MaKH VARCHAR(5),
	@NgayHD DATE,
	@TriGia MONEY
AS
BEGIN
	IF(@MaNV IS NULL OR @MaKH IS NULL OR @NgayHD IS NULL OR @TriGia IS NULL)
		PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'	
	ELSE 
		BEGIN
			INSERT INTO HOADON VALUES(@MaNV, @MaKH,@NgayHD , @TriGia)
		END 
END

EXEC insert_HOADON 'N02','001','2022/04/15',230
EXEC insert_HOADON 'N01','003','2022/03/20',150
EXEC insert_HOADON 'N03','002','2022/02/04',330


SELECT * FROM KHACHHANG
SELECT * FROM NHANVIEN
SELECT * FROM HOADON

--BÀI 3:VIẾT HÀM
/*Viết hàm các tham số đầu vào tương ứng với các cột của
bảng NHANVIEN . Hàm này trả về MaNV thỏa mãn các giá trị được truyền tham số*/
IF OBJECT_ID('f_MaNV') IS NOT NULL 
DROP FUNCTION f_MaNV
GO 
CREATE FUNCTION f_MaNV(@HoTenNV NVARCHAR(50), @DChiNV NVARCHAR(200), @SDTNV VARCHAR(15))
RETURNS NVARCHAR(100)
AS
	BEGIN
		IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE @HoTenNV=HoTenNV and @DChiNV=DChiNV and @SDTNV=SDTNV)
			RETURN N'Không tồn tại khách hàng này'

			RETURN N'Mã khách hàng là:' + CAST((SELECT MaNV FROM NHANVIEN WHERE @HoTenNV=HoTenNV 
											and @DChiNV=DChiNV and @SDTNV=SDTNV) AS VARCHAR(5))
END

PRINT dbo.f_MaNV (N'TRẦN PHƯƠNG NHI',N'HÀ NỘI','0456789567')

---bài 4:tạo view
/*Tạo View lưu thông tin của TOP 2 hóa đơn có trị giá lớn nhất, gồm các thông tin sau:
MaKH, HoTenKH, DChi, MaNV, HoTenNV .*/
IF OBJECT_ID('vi_Top2') IS NOT NULL 
DROP VIEW vi_Top2 
GO
CREATE VIEW vi_Top2
AS
	SELECT TOP 2 KHACHHANG.MaKH, HoTenKH, DChiKH, NHANVIEN.MaNV, HoTenNV,TriGia
	FROM HOADON JOIN KHACHHANG ON HOADON.MaNV = KHACHHANG.MaKH 
				JOIN NHANVIEN ON HOADON.MaKH = NHANVIEN.MaNV
	ORDER BY TriGia DESC

SELECT * FROM vi_Top2

---BÀI 5:THỦ TỤC
/*Viết một SP nhận một tham số đầu vào là TriGia. 
SP này thực hiện thao tác xóa thông tin
khách hàng và nhân viên tương ứng.*/
IF OBJECT_ID('sp_Xoa') IS NOT NULL 
DROP PROC sp_Xoa
GO 
CREATE PROC sp_Xoa @TriGia MONEY
AS 
BEGIN 
	BEGIN TRY 
		BEGIN TRAN
			DECLARE	@Table TABLE(MaNV VARCHAR(5),MaKH VARCHAR(5))
			INSERT INTO @Table SELECT MaNV,MaKH FROM HOADON WHERE @TriGia=TriGia

			DELETE FROM HOADON WHERE MaNV IN (SELECT MaNV FROM @Table)
								  OR MaKH IN (SELECT MaKH FROM @Table)
			DELETE FROM NHANVIEN WHERE MaNV IN (SELECT MaNV FROM @Table)
			DELETE FROM KHACHHANG WHERE MaKH IN (SELECT MaKH FROM @Table)
		COMMIT TRAN 
	END TRY 
	
	BEGIN CATCH
		ROLLBACK TRAN 
	END CATCH 
END  

EXEC dbo.sp_Xoa 230

SELECT * FROM HOADON
SELECT * FROM NHANVIEN
SELECT * FROM KHACHHANG