CREATE DATABASE DE6_DANGKYHOC

IF OBJECT_ID('SINHVIEN') IS NOT NULL 
DROP TABLE SINHVIEN
GO 
CREATE TABLE SINHVIEN
(
	MaSV VARCHAR(10) PRIMARY KEY,
	HoTenSV NVARCHAR(50),
	GioiTinh VARCHAR(5),
	NSinh DATE,
	DChi NVARCHAR(250),
	SDT VARCHAR(20)
)
IF OBJECT_ID('MONHOC') IS NOT NULL 
DROP TABLE MONHOC
GO 
CREATE TABLE MONHOC
(
	MaMH VARCHAR(10) PRIMARY KEY,
	TenMH NVARCHAR(50),
	DChi NVARCHAR(250),
	STChi INT
)
IF OBJECT_ID('DANGKY') IS NOT NULL 
DROP TABLE DANGKY
GO
CREATE TABLE DANGKY
(
	MaSV VARCHAR(10),
	MaMH VARCHAR(10),
	NgayDK DATE,
	HocKy VARCHAR(10),
	PRIMARY KEY(MaSV,MaMH),
	FOREIGN KEY (MaSV) REFERENCES SINHVIEN,
	FOREIGN KEY (MaMH) REFERENCES MONHOC
)
---BAIF 2:

---BẢNG SINHVIEN
IF OBJECT_ID('sp_SINHVIEN') IS NOT NULL 
DROP PROC sp_SINHVIEN
GO 
CREATE PROC sp_SINHVIEN
	@MaSV VARCHAR(10),
	@HoTenSV NVARCHAR(50),
	@GioiTinh VARCHAR(5),
	@NSinh DATE,
	@DChi NVARCHAR(250),
	@SDT VARCHAR(20)
AS
BEGIN
	IF(@MaSV IS NULL OR @HoTenSV IS NULL OR @GioiTinh IS NULL OR @NSinh IS NULL OR @DChi IS NULL OR @SDT IS NULL)
			PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE IF EXISTS(SELECT * FROM SINHVIEN WHERE @MaSV=MaSV)
			PRINT N'Mã sinh viên này đã tồn tại'
	ELSE 
		BEGIN
			INSERT INTO SINHVIEN VALUES(@MaSV,@HoTenSV ,@GioiTinh,@NSinh , @DChi,@SDT)
		END
END

EXEC sp_SINHVIEN 'N01',N'Lê Thị Nga',N'Nữ','2022/04/20',N'Ngõ 99','0335188503'
EXEC sp_SINHVIEN 'N02',N'Lê Thị Nga A',N'Nam','2022/05/25',N'Ngõ 91','0335188456'
EXEC sp_SINHVIEN 'N03',N'Lê Thị Nga B',N'Nữ','2022/03/15',N'Ngõ 89','0335188567'

---BẢNG MONHOC
IF OBJECT_ID('sp_MONHOC') IS NOT NULL 
DROP PROC sp_MONHOC
GO 
CREATE PROC sp_MONHOC
	@MaMH VARCHAR(10),
	@TenMH NVARCHAR(50),
	@DChi NVARCHAR(250),
	@STChi INT
AS
BEGIN
	IF(@MaMH IS NULL OR @TenMH IS NULL OR @DChi IS NULL OR @STChi IS NULL)
			PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE IF EXISTS(SELECT * FROM MONHOC WHERE @MaMH=MaMH)
			PRINT N'Mã môn học này đã tồn tại'
	ELSE 
		BEGIN
			INSERT INTO MONHOC VALUES(@MaMH,@TenMH,@DChi,@STChi)
		END
END

EXEC sp_MONHOC '001',N'Ứng dụng phần mềm',N'Phòng P302',3
EXEC sp_MONHOC '002',N'Xây dựng trang web',N'Phòng F207',5
EXEC sp_MONHOC '003',N'Tiếng Anh',N'Phòng P302',4

----BẢNG DANGKY
IF OBJECT_ID('sp_DANGKY') IS NOT NULL 
DROP PROC sp_DANGKY
GO
CREATE PROC sp_DANGKY
	@MaSV VARCHAR(10),
	@MaMH VARCHAR(10),
	@NgayDK DATE,
	@HocKy VARCHAR(10)
AS
BEGIN
	IF(@MaMH IS NULL OR @MaSV IS NULL OR @NgayDK IS NULL OR @HocKy IS NULL)
			PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE 
		BEGIN
			INSERT INTO DANGKY VALUES(@MaMH,@MaSV,@NgayDK,@HocKy)
		END
END

EXEC sp_DANGKY '001','N02','2022/06/20',N'Kỳ I' 
EXEC sp_DANGKY '002','N03','2022/05/10',N'Kỳ III'
EXEC sp_DANGKY '003','N01','2022/06/05',N'Kỳ II'

SELECT * FROM SINHVIEN
SELECT * FROM MONHOC
SELECT * FROM DANGKY
------------
--BÀI 3:TẠO HÀM
IF OBJECT_ID('f_SINHVIEN') IS NOT NULL 
DROP FUNCTION f_SINHVIEN 
GO 
CREATE FUNCTION f_SINHVIEN(@HoTenSV NVARCHAR(50),@GioiTinh VARCHAR(5),@NSinh DATE,@DChi NVARCHAR(250),@SDT VARCHAR(20))
RETURNS NVARCHAR(100)
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM SINHVIEN WHERE @HoTenSV =HoTenSV AND @GioiTinh=GioiTinh AND @NSinh = NSinh AND @DChi=DChi AND @SDT=SDT)
		RETURN N'Không tồn tại sinh viên này'
	
		RETURN N'Mã sinh viên là:' + CAST((SELECT MaSV FROM SINHVIEN WHERE @HoTenSV =HoTenSV 
		AND @GioiTinh=GioiTinh AND @NSinh = NSinh AND @DChi=DChi AND @SDT=SDT) AS VARCHAR(10))	
END
GO

PRINT dbo.f_SINHVIEN(N'Lê Thị Nga',N'Nữ','2022/04/20',N'Ngõ 99','0335188503')

--BÀI 4: TẠO VIEW
IF OBJECT_ID('vi_Top2') IS NOT NULL 
DROP VIEW vi_Top2
GO 
CREATE VIEW vi_Top2
AS
	SELECT TOP 2 SINHVIEN.MaSV,HoTenSV, MONHOC.DChi, MONHOC.MaMH, TenMH,NgayDK 
	FROM DANGKY JOIN MONHOC ON DANGKY.MaMH=MONHOC.MaMH
				JOIN SINHVIEN ON SINHVIEN.MaSV=DANGKY.MaSV
	ORDER BY NgayDK DESC 

SELECT * FROM vi_Top2

--5. Viết thủ tục
IF OBJECT_ID('sp_Xoa') IS NOT NULL 
DROP PROC sp_Xoa
GO
CREATE PROC sp_Xoa @NgayDK DATE
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			DECLARE @Table TABLE (MaSV VARCHAR(10),MaMH VARCHAR(10))
			INSERT INTO @Table 
			SELECT MaSV,MaMH FROM DANGKY WHERE @NgayDK = NgayDK

			DELETE FROM DANGKY WHERE MaSV in(SELECT MaSV FROM @Table) 
								OR MaMH in(SELECT MaMH FROM @Table)
			DELETE FROM MONHOC WHERE MaMH in(SELECT MaMH FROM @Table)
			DELETE FROM SINHVIEN WHERE MaSV in (SELECT MaSV FROM @Table) 
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH
END

EXEC dbo.sp_Xoa '2022/06/05'

SELECT * FROM DANGKY