CREATE DATABASE De7_PHANCONG

IF OBJECT_ID('NHANVIEN') IS NOT NULL 
DROP TABLE NHANVIEN
GO 
CREATE TABLE NHANVIEN
(
	MaNV VARCHAR(10) PRIMARY KEY,
	HoTenNV NVARCHAR(50),
	GioiTinh VARCHAR(5),
	NSinh DATE, 
	DChi NVARCHAR(200)
)

IF OBJECT_ID('DUAN') IS NOT NULL 
DROP TABLE DUAN
GO 
CREATE TABLE DUAN
(
	MaDA VARCHAR(10) PRIMARY KEY,
	TenDA NVARCHAR(50),
	LoaiDA VARCHAR(20),
	GiaTri MONEY
)

IF OBJECT_ID('PHANCONG') IS NOT NULL 
DROP TABLE PHANCONG
GO 
CREATE TABLE PHANCONG
(
	MaNV VARCHAR(10),
	MaDA VARCHAR(10),
	NgayPC DATE,
	NgayHT DATE,
	PRIMARY KEY(MaNV,MaDA),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN ,
	FOREIGN KEY (MaDA) REFERENCES DUAN
)

---BÀI 2:
--BẢNG NHANVIEN
IF OBJECT_ID('insert_NHANVIEN') IS NOT NULL 
DROP PROC insert_NHANVIEN
GO 
CREATE PROC insert_NHANVIEN
	@MaNV VARCHAR(10),
	@HoTenNV NVARCHAR(50),
	@GioiTinh VARCHAR(5),
	@NSinh DATE, 
	@DChi NVARCHAR(200)
AS
BEGIN
	IF(@MaNV IS NULL OR @HoTenNV IS NULL OR
	  @GioiTinh IS NULL OR @NSinh IS NULL OR  @DChi IS NULL)
		PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE IF EXISTS(SELECT * FROM NHANVIEN WHERE @MaNV=MaNV)
		PRINT N'MÃ NHÂN VIÊN ĐÃ TỒN TẠI'
	ELSE 
		BEGIN
			INSERT INTO NHANVIEN VALUES(@MaNV ,@HoTenNV ,@GioiTinh,@NSinh , @DChi)
		END
END
EXEC insert_NHANVIEN 'N01',N'Lê Thị Nga',N'Nữ','2003/04/20',N'Ngõ 99'
EXEC insert_NHANVIEN 'N02',N'Lê Thị Nga A',N'Nam','2002/02/15',N'Ngõ 91'
EXEC insert_NHANVIEN 'N03',N'Lê Thị Nga B',N'Nữ','2001/04/20',N'Ngõ 95'
-----------------BẢNG DUAN-----------------------------
IF OBJECT_ID('insert_DUAN') IS NOT NULL 
DROP PROC insert_DUAN
GO 
CREATE PROC insert_DUAN
	@MaDA VARCHAR(10),
	@TenDA NVARCHAR(50),
	@LoaiDA VARCHAR(20),
	@GiaTri MONEY
AS 
BEGIN
	IF(@MaDA  IS NULL OR @TenDA IS NULL OR
	 @LoaiDA IS NULL OR @GiaTri IS NULL)
		PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE IF EXISTS(SELECT * FROM DUAN WHERE @MaDA=MaDA)
		PRINT N'MÃ NHÂN VIÊN ĐÃ TỒN TẠI'
	ELSE 
		BEGIN
			INSERT INTO DUAN VALUES(@MaDA ,@TenDA ,@LoaiDA ,@GiaTri)
		END
END
EXEC insert_DUAN  '001',N'DỰ ÁN 1',N'LOẠI 1',2000
EXEC insert_DUAN  '002',N'DỰ ÁN 2',N'LOẠI 2',1000
EXEC insert_DUAN  '003',N'DỰ ÁN 3',N'LOẠI 3',3000
-------------BẢNG PHANCONG--------------------------------------
IF OBJECT_ID('insert_PHANCONG') IS NOT NULL 
DROP PROC insert_PHANCONG
GO 
CREATE PROC insert_PHANCONG
	@MaNV VARCHAR(10),
	@MaDA VARCHAR(10),
	@NgayPC DATE,
	@NgayHT DATE	
AS
BEGIN
	IF(@MaNV  IS NULL OR @MaDA IS NULL OR
	 @NgayPC IS NULL OR @NgayHT IS NULL)
		PRINT N'THIẾU THÔNG TIN ĐẦU VÀO'
	ELSE 
		BEGIN
			INSERT INTO PHANCONG VALUES(@MaNV,@MaDA, @NgayPC,@NgayHT)
		END
END

EXEC insert_PHANCONG 'N01','003','2021/05/25','2022/05/25'
EXEC insert_PHANCONG 'N02','001','2021/06/15','2021/09/28'
EXEC insert_PHANCONG 'N03','002','2021/07/20','2022/03/26'

SELECT * FROM NHANVIEN
SELECT * FROM DUAN
SELECT * FROM PHANCONG

---BÀI 3:TẠO HÀM
/*Viết hàm các tham số đầu vào tương ứng với các cột của 
bảng DUAN. Hàm này trả về
MaDA thỏa mãn các giá trị được truyền tham số.*/
IF OBJECT_ID('f_DUAN') IS NOT NULL 
DROP FUNCTION f_DUAN
GO 
CREATE FUNCTION f_DUAN
(
	@TenDA NVARCHAR(50),
	@LoaiDA VARCHAR(20),
	@GiaTri MONEY
)
RETURNS NVARCHAR(100)
AS 
BEGIN
	IF NOT EXISTS (SELECT * FROM DUAN WHERE @TenDA=TenDA AND  @LoaiDA =LoaiDA AND @GiaTri=GiaTri)
		RETURN N'KHÔNG TỒN TẠI'

		RETURN N'MÃ DỰ ÁN LÀ:' + CAST((SELECT MaDA FROM DUAN 
		WHERE @TenDA=TenDA AND  @LoaiDA =LoaiDA AND @GiaTri=GiaTri) AS VARCHAR(10))

END
GO

PRINT dbo.f_DUAN (N'DỰ ÁN 1',N'LOẠI 1',2000)

--BAIF 4:TAOJ VIEW
IF OBJECT_ID('vi_Top2') IS NOT NULL 
DROP VIEW vi_Top2
GO 
CREATE VIEW vi_Top2
AS 
	SELECT TOP 2 DUAN.MaDA,TenDA, LoaiDA, HoTenNV, NgayHT ,GiaTri
	FROM DUAN JOIN PHANCONG ON PHANCONG.MaDA = DUAN.MaDA
				JOIN NHANVIEN ON  PHANCONG.MaNV=NHANVIEN.MaNV
	ORDER BY GiaTri DESC

SELECT * FROM vi_Top2

--- CÂU 5:VIẾT THỦ TỤC XÓA
/*Viết một SP nhận một tham số đầu vào là NgayHT. 
SP này thực hiện thao tác xóa thông
tin nhân viên và dự án tương ứng*/

IF OBJECT_ID('sp_Xoa') IS NOT NULL 
DROP PROC sp_Xoa 
GO
CREATE PROC sp_Xoa @NgayHT DATE
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			DECLARE @Table TABLE(MaNV VARCHAR(10),MaDA VARCHAR(10))
			INSERT INTO @Table SELECT  MaNV,MaDA FROM PHANCONG WHERE @NgayHT=NgayHT

			DELETE FROM PHANCONG WHERE MaDA IN(SELECT MaDA FROM @Table) 
									OR MaNV IN(SELECT MaNV FROM @Table)
			DELETE FROM DUAN WHERE MaDA IN(SELECT MaDA FROM @Table) 
			DELETE FROM NHANVIEN WHERE MaNV IN(SELECT MaNV FROM @Table)
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH	
END

EXEC dbo.sp_Xoa '2022/03/26'

SELECT * FROM PHANCONG