CREATE DATABASE QUANLYNHANSU

IF OBJECT_ID('PHONGBAN') IS NOT NULL 
DROP TABLE   PHONGBAN
GO 
CREATE TABLE PHONGBAN
(
	MAPB VARCHAR(10) PRIMARY KEY,
	TENPB NVARCHAR(50)
)
IF OBJECT_ID('NHANVIEN') IS NOT NULL 
DROP TABLE   NHANVIEN
GO 
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	GIOITINH VARCHAR(10),
	LUONG MONEY,
	MAPB VARCHAR(10),
	FOREIGN KEY (MAPB) REFERENCES  PHONGBAN
)

IF OBJECT_ID('CHAMCONG') IS NOT NULL 
DROP TABLE   CHAMCONG
GO 
CREATE TABLE CHAMCONG
(
	MACONG VARCHAR(10) PRIMARY KEY,
	MANV VARCHAR(10),
	THANG INT,
	SONGAYLV INT,
	NGPHEP INT,
	NGKPHEP INT,
	FOREIGN KEY (MANV) REFERENCES  NHANVIEN
)

---CÂU 2;
--BẢNG PHONGBAN
IF OBJECT_ID('sp_PHONGBAN') IS NOT NULL 
DROP PROC   sp_PHONGBAN
GO 
CREATE PROC sp_PHONGBAN
	@MAPB VARCHAR(10),
	@TENPB NVARCHAR(50)
AS
BEGIN 
	IF(@MAPB IS NULL OR @TENPB IS NULL)
		PRINT N'THIẾU THÔNG TIN'
	ELSE IF EXISTS(SELECT MAPB FROM PHONGBAN WHERE @MAPB=MAPB AND  @TENPB=TENPB)
		PRINT N'ĐÃ TỒN TẠI'
	ELSE 
		BEGIN
			INSERT INTO PHONGBAN VALUES(@MAPB,@TENPB)
		END
END

---BẢNG NHANVIEN
IF OBJECT_ID('sp_NHANVIEN') IS NOT NULL 
DROP PROC   sp_NHANVIEN
GO 
CREATE PROC sp_NHANVIEN
	@MANV VARCHAR(10),
	@HOTEN NVARCHAR(50),
	@GIOITINH VARCHAR(10),
	@LUONG MONEY,
	@MAPB VARCHAR(10)
AS 
BEGIN 
	IF(@MANV IS NULL OR @HOTEN IS NULL OR @GIOITINH IS NULL OR @LUONG IS NULL OR @MAPB IS NULL)
		PRINT N'THIẾU THÔNG TIN'
	
	ELSE IF  NOT EXISTS(SELECT * FROM PHONGBAN WHERE @MAPB =MAPB)
		PRINT N'KHÔNG  TỒN TẠI'
	ELSE IF EXISTS(SELECT * FROM NHANVIEN WHERE @MANV=MANV)
		PRINT N'ĐÃ TỒN TẠI'
	ELSE
		BEGIN
			INSERT INTO NHANVIEN VALUES(@MANV,@HOTEN, @GIOITINH, @LUONG , @MAPB)
		END
END

------
IF OBJECT_ID('sp_CHAMCONG') IS NOT NULL 
DROP PROC  sp_CHAMCONG
GO 
CREATE PROC sp_CHAMCONG
	@MACONG VARCHAR(10),
	@MANV VARCHAR(10),
	@THANG INT,
	@SONGAYLV INT,
	@NGPHEP INT,
	@NGKPHEP INT
AS
BEGIN
	IF(@MACONG IS NULL OR @MANV IS NULL OR @THANG IS NULL OR @SONGAYLV IS NULL OR @NGPHEP IS NULL OR @NGKPHEP IS NULL)
		PRINT N'THIẾU THÔNG TIN'
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE @MANV=MANV)
		PRINT N'ĐÃ TỒN TẠI'
	ELSE IF  EXISTS(SELECT * FROM CHAMCONG WHERE @MACONG =MACONG)
		PRINT N'KHÔNG  TỒN TẠI'
	ELSE
		BEGIN
			INSERT INTO CHAMCONG VALUES(@MACONG,@MANV,@THANG,@SONGAYLV, @NGPHEP,@NGKPHEP)
		END
END 


EXEC sp_PHONGBAN 'P01',N'PHÒNG NHÂN SỰ'
EXEC sp_PHONGBAN 'P02',N'PHÒNG HÀNH CHÍNH'
EXEC sp_PHONGBAN 'P03',N'PHÒNG IT'

EXEC sp_NHANVIEN 'N01',N'LÊ THỊ NGA',N'NỮ',560,'P02'
EXEC sp_NHANVIEN 'N02',N'LÊ THỊ NGA A',N'NAM',460,'P03'
EXEC sp_NHANVIEN 'N03',N'LÊ THỊ NGA C',N'NỮ',760,'P01'

EXEC sp_CHAMCONG 'C01','N02',3,25,1,0
EXEC sp_CHAMCONG 'C02','N03',4,26,2,1
EXEC sp_CHAMCONG 'C03','N01',5,27,3,2

SELECT * FROM PHONGBAN
SELECT * FROM NHANVIEN
SELECT * FROM CHAMCONG
--CÂU3 :
IF OBJECT_ID('f_NHANVIEN') IS NOT NULL 
DROP FUNCTION   f_NHANVIEN
GO 
CREATE FUNCTION f_NHANVIEN
(
	@HOTEN NVARCHAR(50),
	@GIOITINH VARCHAR(10),
	@LUONG MONEY,
	@MAPB VARCHAR(10)
)
RETURNS NVARCHAR(100)
AS 
BEGIN 
	IF NOT EXISTS (SELECT * FROM NHANVIEN WHERE @HOTEN=HOTEN AND @GIOITINH=GIOITINH AND @LUONG=LUONG AND @MAPB=MAPB)
			
			RETURN N'Không có thông tin trùng khớp'

			RETURN N'Mã nhân viên là:'+CAST((SELECT MANV FROM NHANVIEN 
			WHERE @HOTEN=HOTEN AND @GIOITINH=GIOITINH AND @LUONG=LUONG AND @MAPB=MAPB) AS VARCHAR(10))
END

PRINT dbo.f_NHANVIEN (N'LÊ THỊ NGA',N'NỮ',560,'P02')

--CÂU 4: VIEW
IF OBJECT_ID('vi_Top2') IS NOT NULL 
DROP VIEW   vi_Top2
GO 
CREATE VIEW vi_Top2
AS
	SELECT TOP 2 PHONGBAN.MAPB,TENPB,COUNT(MANV) AS N'Số lượng' 
	FROM NHANVIEN JOIN PHONGBAN ON PHONGBAN.MAPB=NHANVIEN.MAPB
	GROUP BY PHONGBAN.MAPB,TENPB
	ORDER BY  COUNT(MANV)
SELECT * FROM vi_Top2

---CÂU 5:
IF OBJECT_ID('sp_Xoa') IS NOT NULL 
DROP PROC   sp_Xoa
GO 
CREATE PROC sp_Xoa @SoNgayPhep INT 
AS 
BEGIN 
	BEGIN TRY 
		BEGIN TRAN 
			DECLARE @Table TABLE (MACONG VARCHAR(10),MANV VARCHAR(10))
			INSERT INTO @Table 
			SELECT MACONG,MANV FROM CHAMCONG WHERE NGPHEP > @SoNgayPhep

			DELETE FROM CHAMCONG WHERE MACONG IN (SELECT MACONG FROM @Table)
			DELETE FROM NHANVIEN WHERE MANV IN (SELECT MANV FROM @Table)
		COMMIT TRAN 
	END TRY 
	
	BEGIN CATCH 
		ROLLBACK TRAN 
	END CATCH 
END 

EXEC sp_Xoa 2

SELECT * FROM CHAMCONG